title: Daniel Cornock
email: daniel_cornock@hotmail.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.danielcornock.co.uk' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: danielcornock
github_username: danielcornock
permalink: /articles/:title
image_dir: /assets/images/

include: ['_pages']

# Build settings
markdown: kramdown

collections:
  projects:
    output: true

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post/post'
  - scope:
      path: ''
      type: 'projects'
    values:
      layout: 'post/post'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
