title: Daniel Cornock
email: daniel_cornock@hotmail.co.uk
description: >-
  Personal website and blog of Daniel Cornock. Take a look at my projects and articles that I write about software development.
baseurl: ''
url: 'https://www.danielcornock.co.uk'
twitter_username: danielcornock
github_username: danielcornock
permalink: /articles/:title
image_dir: /assets/images/

include: ['_pages']

# Build settings
markdown: kramdown

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post/post'
  - scope:
      path: ''
      type: 'projects'
    values:
      layout: 'post/post'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
